import Link from "next/link";
import { notFound } from "next/navigation";
import { brand } from "@/lib/theme";

/**
 * SCR-020: policy pages, US and Canada.
 *
 * [要確認] Every one of these needs counsel's review before launch. What is
 * settled is the shape: terms, privacy written against CCPA/CPRA and PIPEDA,
 * a content policy, DMCA, and a companion-AI safeguards page that states the
 * disclosures NY GBL Art. 47 and CA SB 243 require.
 */
const DOCS: Record<string, { title: string; body: string }> = {
  terms: {
    title: "Terms of Service",
    body: `These terms govern your use of ${brand.name} ("the Service").

1. What this is. ${brand.name} is an interactive fiction service. Every character is
   fictional and every response is generated by an AI language model. Nothing produced
   here is a statement of fact, advice, or a communication from a person.

2. Who can use it. You must be 13 or older. Stories rated 18+ are shown only to readers
   who have confirmed they are 18 or older.

3. Your work stays yours. If you publish a story, you keep its copyright. You grant us a
   non-exclusive, revocable licence to host, display and let readers play it, and to show
   it in discovery surfaces. You can unpublish at any time. We do not buy your copyright,
   and we do not ask for exclusivity as a condition of earning from your work.

4. Original work only. Do not publish work built on someone else's characters, worlds or
   likeness. See the Content Policy.

5. What we owe you. Standard generations are unlimited on every plan, including free.
   Correcting your Canon is never metered. Credits you buy do not expire, and are not
   forfeited if you close your account.

6. [TO CONFIRM] Governing law, entity details, arbitration and limitation of liability to be
   settled with counsel before launch.`,
  },
  privacy: {
    title: "Privacy Policy",
    body: `What we collect, and what we do with it.

WHAT WE COLLECT
- Your account: email address, display name, date of birth, and the plan you are on.
- What you play: routes, messages, canon facts, stats and endings.
- How you use the service: pages visited, features used, and diagnostic logs.

WHAT WE DO WITH IT
- Run the service: continue your stories, remember your canon, apply your plan.
- Keep people safe: detect content that violates the Content Policy, and detect
  expressions of crisis so we can show you real help instead of fiction.
- Improve the service in aggregate.

WHAT WE DO NOT DO
- We do not sell or share your personal information for cross-context behavioural
  advertising, as those terms are defined by the CCPA/CPRA.
- We do not use your private stories to train models without your explicit opt-in.

YOUR RIGHTS
- California (CCPA/CPRA): you may request access, correction, deletion and portability,
  and you may limit the use of sensitive personal information. We will not discriminate
  against you for exercising any of these.
- Canada (PIPEDA): you may access your personal information and challenge its accuracy.
- Everywhere: deleting your account removes your personal information and unpublishes
  your stories.

CHILDREN
The service is not directed to children under 13 and we do not knowingly collect their
personal information.

[TO CONFIRM] Retention periods, subprocessors, international transfer basis, and the Quebec
Law 25 position on French-language disclosure to be settled with counsel before launch.`,
  },
  content: {
    title: "Content Policy",
    body: `Everyone who publishes on ${brand.name} agrees to this.

ORIGINAL WORK ONLY
Do not use characters, settings or titles from existing anime, manga, games, novels,
films or television, and do not depict real people. Stories that do are blocked at
publish. We do not run a fan-fiction category while banning fan fiction in policy.

RATINGS
- All ages: attraction, longing and tension. No sexual content. No graphic violence.
- 18+: charged, suggestive, sensual writing — held breath, a fade to black. Shown only to
  readers who have confirmed their age.

Explicit sexual content is not published here at any rating.

NEVER, AT ANY RATING
- Sexual content involving anyone who is, or reads as, a minor.
- Non-consensual sexual content presented as desirable.
- Incest, or sexual content involving animals.
- Content that encourages self-harm, suicide, or violence against real people or groups.
- Content that sexualises real, identifiable people.

WHAT HAPPENS IF YOU CROSS A LINE
The story is unpublished and you are told which rule it broke and why. Repeated or severe
violations end the account. You can appeal any decision.

REPORTING
Every story page has a report control. Reports are reviewed by a person.`,
  },
  safety: {
    title: "AI Safeguards",
    body: `${brand.name} is a companion-style AI service, and we treat it as one.

YOU ARE TALKING TO AN AI
Every narrator, character and reply on this service is generated by an AI language model.
No response comes from a person. We say so when you start a story, and we interrupt long
sessions to say it again — at least every three hours for adults, and every hour for
readers under 18.

BREAKS
Readers under 18 are reminded to take a break on a shorter cycle. Any reader can end a
session from the intermission screen.

IF YOU ARE IN CRISIS
If what you write suggests you may be thinking about harming yourself, we stop generating
fiction and show you real crisis resources instead. We would rather interrupt a story than
answer that in character.

- United States and Canada: 988 Suicide & Crisis Lifeline — call or text 988
- United States: Crisis Text Line — text HOME to 741741

WHAT WE LOG, AND WHY
We record that a disclosure was shown, that a break reminder was shown, and that crisis
resources were surfaced. These records exist so we can show that we did what New York
General Business Law Article 47 and California SB 243 require of us.

WHAT WE DO NOT DO
We do not present the AI as a licensed professional, and we do not let a character claim
to be a person.`,
  },
  dmca: {
    title: "Copyright and DMCA",
    body: `We publish original work only, and we act on notices quickly.

TO FILE A NOTICE
Send our designated agent: your signature, identification of the work infringed,
identification of the material on ${brand.name} and its URL, your contact details, a
statement of good-faith belief, and a statement under penalty of perjury that your notice
is accurate and that you are authorised to act.

COUNTER-NOTICE
If your story was removed and you believe that was a mistake, you may file a
counter-notice with the same detail. We will inform the complainant and, absent a court
action, may restore the material.

REPEAT INFRINGERS
Accounts that repeatedly infringe are terminated.

[TO CONFIRM] Designated agent name, address and registration with the U.S. Copyright Office to
be completed before launch.`,
  },
};

const NAV: [string, string][] = [
  ["terms", "Terms"],
  ["privacy", "Privacy"],
  ["content", "Content Policy"],
  ["safety", "AI Safeguards"],
  ["dmca", "DMCA"],
];

export function generateStaticParams() {
  return Object.keys(DOCS).map((doc) => ({ doc }));
}

export default async function LegalPage({ params }: { params: Promise<{ doc: string }> }) {
  const { doc } = await params;
  const content = DOCS[doc];
  if (!content) notFound();
  return (
    <main className="px-5 py-8">
      <Link href="/me" className="text-sm" style={{ color: "var(--c-textMuted)" }}>
        ← Back
      </Link>
      <h1 className="mt-4 text-xl font-bold">{content.title}</h1>
      <div className="mt-4 whitespace-pre-wrap text-sm leading-relaxed">{content.body}</div>
      <nav className="mt-8 flex flex-wrap gap-3 text-xs" style={{ color: "var(--c-accent)" }}>
        {NAV.map(([slug, label]) => (
          <Link key={slug} href={`/legal/${slug}`}>
            {label}
          </Link>
        ))}
      </nav>
    </main>
  );
}
